In [16]:
import pandas as pd
import numpy as np

In [18]:
pip install pyxlsb

Requirement already satisfied: pyxlsb in d:\users\hp 15\anaconda3\lib\site-packages (1.0.10)
Note: you may need to restart the kernel to use updated packages.

In [22]:
import pandas as pd

df = pd.read_excel(
    r"C:\Users\HP 15\Desktop\project\DEEP\emissions_by_unit_and_fuel_type_c_d_aa.xlsb",
    engine="pyxlsb"
)

df.head()

,This file contains data collected by the Greenhouse Gas Reporting Program for 2011-2023,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,This data was reported to EPA by facilities as...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,All emissions data is presented in units of me...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,** A file containing matches between each GHGR...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,** Additional information on facility location...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"*** Explanation about what an ""Electricity Gen...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
df.head()

,This file contains data collected by the Greenhouse Gas Reporting Program for 2011-2023,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,This data was reported to EPA by facilities as...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,All emissions data is presented in units of me...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,** A file containing matches between each GHGR...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,** Additional information on facility location...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"*** Explanation about what an ""Electricity Gen...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
df.tail()

,This file contains data collected by the Greenhouse Gas Reporting Program for 2011-2023,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
268779,1003318,110043796675,ZYBACH CRYOGENIC PLANT,Briscoe,TX,211111,2015,"C,W",Petroleum and Natural Gas Systems,GP-Zybach,OCS (Other combustion source),Tier1/2/3,32,33757.8,16,19.072,0
268780,1003318,110043796675,ZYBACH CRYOGENIC PLANT,Briscoe,TX,211111,2014,"C,W",Petroleum and Natural Gas Systems,GP-Zybach,OCS (Other combustion source),Tier1/2/3,32,32901.2,15.5,18.476,0
268781,1003318,110043796675,ZYBACH CRYOGENIC PLANT,Briscoe,TX,211111,2013,"C,W",Petroleum and Natural Gas Systems,GP-Zybach,OCS (Other combustion source),Tier1/2/3,32,42700.7,20.25,24.138,0
268782,1003318,110043796675,ZYBACH CRYOGENIC PLANT,Briscoe,TX,211111,2012,"C,W",Petroleum and Natural Gas Systems,GP-Zybach,OCS (Other combustion source),Tier1/2/3,32,46840.7,22,26.224,0
268783,1003318,110043796675,ZYBACH CRYOGENIC PLANT,Briscoe,TX,211111,2011,"C,W",Petroleum and Natural Gas Systems,GP-Zybach,OCS (Other combustion source),Tier1/2/3,32,53482.2,25.25,30.098,0

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 268784 entries, 0 to 268783
Data columns (total 17 columns):
 #   Column                                                                                   Non-Null Count   Dtype
---  ------                                                                                   --------------   -----
 0   This file contains data collected by the Greenhouse Gas Reporting Program for 2011-2023  268784 non-null  object
 1   Unnamed: 1                                                                               239089 non-null  object
 2   Unnamed: 2                                                                               268779 non-null  object
 3   Unnamed: 3                                                                               268779 non-null  object
 4   Unnamed: 4                                                                               268779 non-null  object
 5   Unnamed: 5                                                                               268763 non-null  object
 6   Unnamed: 6                                                                               268779 non-null  object
 7   Unnamed: 7                                                                               268779 non-null  object
 8   Unnamed: 8                                                                               268779 non-null  object
 9   Unnamed: 9                                                                               268779 non-null  object
 10  Unnamed: 10                                                                              259676 non-null  object
 11  Unnamed: 11                                                                              264851 non-null  object
 12  Unnamed: 12                                                                              215247 non-null  object
 13  Unnamed: 13                                                                              268779 non-null  object
 14  Unnamed: 14                                                                              268779 non-null  object
 15  Unnamed: 15                                                                              268779 non-null  object
 16  Unnamed: 16                                                                              264851 non-null  object
dtypes: object(17)
memory usage: 34.9+ MB

In [30]:
df.drop(index=df.index[:5], inplace=True)

# Set the first row as header
df.columns = df.iloc[0]

# Drop the row that became the header
df = df.iloc[1:].reset_index(drop=True)

In [32]:
df.head()

5,Facility Id,FRS Id,Facility Name,City,State,Primary NAICS Code,Reporting Year,Industry Type (subparts),Industry Type (sectors),Unit Name,Unit Type,Unit Reporting Method,Unit Maximum Rated Heat Input Capacity (mmBTU/hr),Unit CO2 emissions (non-biogenic),Unit Methane (CH4) emissions,Unit Nitrous Oxide (N2O) emissions,Unit Biogenic CO2 emissions (metric tons)
0,1001155,110000397516,1500 South Tibbs LLC d/b/a Aurorium Indianapol...,Indianapolis,IN,325199,2023,C,Chemicals,GP-1,NaN,Tier1/2/3,91.8,64740.5,30.5,36.356,0
1,1012147,NaN,17Z Gas Plant - Chevron USA Inc.,McKittrick,CA,211130,2018,"C,NN,W","Natural Gas and Natural Gas Liquids Suppliers,...",CP-03.00,OCS (Other combustion source),Tier1/2/3,30,3304.7,1.5,1.788,0
2,1012147,NaN,17Z Gas Plant - Chevron USA Inc.,McKittrick,CA,211130,2018,"C,NN,W","Natural Gas and Natural Gas Liquids Suppliers,...",CP-03.01,OCS (Other combustion source),Tier1/2/3,30,0.2,0,0,0
3,1012147,NaN,17Z Gas Plant - Chevron USA Inc.,McKittrick,CA,211130,2018,"C,NN,W","Natural Gas and Natural Gas Liquids Suppliers,...",CP-03.02,OCS (Other combustion source),Tier1/2/3,30,175,0,0,0
4,1012147,NaN,17Z Gas Plant - Chevron USA Inc.,McKittrick,CA,211130,2017,"C,NN,W","Natural Gas and Natural Gas Liquids Suppliers,...",CP-03.00,OCS (Other combustion source),Tier1/2/3,30,9106.1,4.25,5.066,0

In [34]:
df.tail()

5,Facility Id,FRS Id,Facility Name,City,State,Primary NAICS Code,Reporting Year,Industry Type (subparts),Industry Type (sectors),Unit Name,Unit Type,Unit Reporting Method,Unit Maximum Rated Heat Input Capacity (mmBTU/hr),Unit CO2 emissions (non-biogenic),Unit Methane (CH4) emissions,Unit Nitrous Oxide (N2O) emissions,Unit Biogenic CO2 emissions (metric tons)
268773,1003318,110043796675,ZYBACH CRYOGENIC PLANT,Briscoe,TX,211111,2015,"C,W",Petroleum and Natural Gas Systems,GP-Zybach,OCS (Other combustion source),Tier1/2/3,32,33757.8,16,19.072,0
268774,1003318,110043796675,ZYBACH CRYOGENIC PLANT,Briscoe,TX,211111,2014,"C,W",Petroleum and Natural Gas Systems,GP-Zybach,OCS (Other combustion source),Tier1/2/3,32,32901.2,15.5,18.476,0
268775,1003318,110043796675,ZYBACH CRYOGENIC PLANT,Briscoe,TX,211111,2013,"C,W",Petroleum and Natural Gas Systems,GP-Zybach,OCS (Other combustion source),Tier1/2/3,32,42700.7,20.25,24.138,0
268776,1003318,110043796675,ZYBACH CRYOGENIC PLANT,Briscoe,TX,211111,2012,"C,W",Petroleum and Natural Gas Systems,GP-Zybach,OCS (Other combustion source),Tier1/2/3,32,46840.7,22,26.224,0
268777,1003318,110043796675,ZYBACH CRYOGENIC PLANT,Briscoe,TX,211111,2011,"C,W",Petroleum and Natural Gas Systems,GP-Zybach,OCS (Other combustion source),Tier1/2/3,32,53482.2,25.25,30.098,0

In [36]:
df.isnull().sum()

5
Facility Id                                              0
FRS Id                                               29690
Facility Name                                            0
City                                                     0
State                                                    0
Primary NAICS Code                                      16
Reporting Year                                           0
Industry Type (subparts)                                 0
Industry Type (sectors)                                  0
Unit Name                                                0
Unit Type                                             9103
Unit Reporting Method                                 3928
Unit Maximum Rated Heat Input Capacity (mmBTU/hr)    53532
Unit CO2 emissions (non-biogenic)                        0
Unit Methane (CH4) emissions                             0
Unit Nitrous Oxide (N2O) emissions                       0
Unit Biogenic CO2 emissions (metric tons)             3928
dtype: int64

In [38]:
df.replace(['NaN', 'nan', 'None'], np.nan, inplace=True)

C:\Users\HP 15\AppData\Local\Temp\ipykernel_30472\3553819837.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace(['NaN', 'nan', 'None'], np.nan, inplace=True)

In [39]:
df.isnull().sum()

5
Facility Id                                              0
FRS Id                                               29690
Facility Name                                            0
City                                                     0
State                                                    0
Primary NAICS Code                                      16
Reporting Year                                           0
Industry Type (subparts)                                 0
Industry Type (sectors)                                  0
Unit Name                                                0
Unit Type                                             9103
Unit Reporting Method                                 3928
Unit Maximum Rated Heat Input Capacity (mmBTU/hr)    53532
Unit CO2 emissions (non-biogenic)                        0
Unit Methane (CH4) emissions                             0
Unit Nitrous Oxide (N2O) emissions                       0
Unit Biogenic CO2 emissions (metric tons)             3928
dtype: int64

In [42]:
df.to_csv("Green house.csv", index=False)

In [44]:
df.drop("FRS Id", axis=1, inplace=True)

So this column was dropped because it has null values and the column is used as a unique I dentfiyer for that we have facility ID so we have no use for this column

In [47]:
df.isnull().sum()

5
Facility Id                                              0
Facility Name                                            0
City                                                     0
State                                                    0
Primary NAICS Code                                      16
Reporting Year                                           0
Industry Type (subparts)                                 0
Industry Type (sectors)                                  0
Unit Name                                                0
Unit Type                                             9103
Unit Reporting Method                                 3928
Unit Maximum Rated Heat Input Capacity (mmBTU/hr)    53532
Unit CO2 emissions (non-biogenic)                        0
Unit Methane (CH4) emissions                             0
Unit Nitrous Oxide (N2O) emissions                       0
Unit Biogenic CO2 emissions (metric tons)             3928
dtype: int64

In [49]:
df[df["Primary NAICS Code"].isna()]

5,Facility Id,Facility Name,City,State,Primary NAICS Code,Reporting Year,Industry Type (subparts),Industry Type (sectors),Unit Name,Unit Type,Unit Reporting Method,Unit Maximum Rated Heat Input Capacity (mmBTU/hr),Unit CO2 emissions (non-biogenic),Unit Methane (CH4) emissions,Unit Nitrous Oxide (N2O) emissions,Unit Biogenic CO2 emissions (metric tons)
14191,1013060,Arcosa Lightweight Indiana,Mooresville,IN,NaN,2022,C,Other,GP-Kilns,OCS (Other combustion source),Tier1/2/3,100.00,51520.8,24.50,29.204,0.0
25848,1000230,Blue Ridge Paper Products LLC,CANTON,NC,NaN,2022,"AA,C,TT","Pulp and Paper, Waste",GP-1,OCS (Other combustion source),Tier1/2/3,1.35,74.3,0.00,0.298,0.0
25849,1000230,Blue Ridge Paper Products LLC,CANTON,NC,NaN,2022,"AA,C,TT","Pulp and Paper, Waste",GP-2,OCS (Other combustion source),Tier1/2/3,4.00,4776.0,2.25,2.682,0.0
25850,1000230,Blue Ridge Paper Products LLC,CANTON,NC,NaN,2022,"AA,C,TT","Pulp and Paper, Waste",Lime Kiln No.4,Pulp Mill Lime Kiln,NaN,NaN,13545.6,15.75,0.298,NaN
25851,1000230,Blue Ridge Paper Products LLC,CANTON,NC,NaN,2022,"AA,C,TT","Pulp and Paper, Waste",Lime Kiln No.5,Pulp Mill Lime Kiln,NaN,NaN,25324.0,28.75,0.298,NaN
25852,1000230,Blue Ridge Paper Products LLC,CANTON,NC,NaN,2022,"AA,C,TT","Pulp and Paper, Waste",PB - No. 1 Natural Gas Package Boiler,"OB (Boiler, other)",Tier1/2/3,225.00,71903.0,34.00,40.528,0.0
25853,1000230,Blue Ridge Paper Products LLC,CANTON,NC,NaN,2022,"AA,C,TT","Pulp and Paper, Waste",PB - No. 2 Natural Gas Package Boiler,"OB (Boiler, other)",Tier1/2/3,225.00,72645.8,34.25,40.826,0.0
25854,1000230,Blue Ridge Paper Products LLC,CANTON,NC,NaN,2022,"AA,C,TT","Pulp and Paper, Waste",PB - No. 4,"PCT (Pulverized coal, tangentially-fired)",Tier1/2/3,535.00,347831.7,907.50,1571.056,0.0
25855,1000230,Blue Ridge Paper Products LLC,CANTON,NC,NaN,2022,"AA,C,TT","Pulp and Paper, Waste",PB - Riley Bark,S (Stoker Boiler),Tier1/2/3,380.00,106365.4,420.50,1335.040,74739.8
25856,1000230,Blue Ridge Paper Products LLC,CANTON,NC,NaN,2022,"AA,C,TT","Pulp and Paper, Waste",PB - Riley Coal,"PCWD (Pulverized coal, wall-fired, dry bottom)",Tier1/2/3,399.00,189537.1,467.00,804.898,0.0
25857,1000230,Blue Ridge Paper Products LLC,CANTON,NC,NaN,2022,"AA,C,TT","Pulp and Paper, Waste",Recovery Furnace No.10,Chemical Recovery Furnace,NaN,NaN,18858.4,233.50,610.602,NaN
25858,1000230,Blue Ridge Paper Products LLC,CANTON,NC,NaN,2022,"AA,C,TT","Pulp and Paper, Waste",Recovery Furnace No.11,Chemical Recovery Furnace,NaN,NaN,13029.3,253.00,663.348,NaN
70615,1005704,DUNN PAPER INC.,PORT HURON,MI,NaN,2022,C,Other,GP-Boilers & Process/Space Heaters,OCS (Other combustion source),Tier1/2/3,94.70,14038.6,6.50,7.748,0.0
172374,1000248,"Otsego Paper, Inc.",OTSEGO,MI,NaN,2022,C,Other,GP-Mill plus package boiler,OCS (Other combustion source),Tier1/2/3,242.00,727.6,0.25,0.298,0.0
172375,1000248,"Otsego Paper, Inc.",OTSEGO,MI,NaN,2022,C,Other,North Turbine 0024,"CCCT (CC (Turbine, combined cycle))",Tier1/2/3,293.90,49618.2,23.50,28.012,0.0
172376,1000248,"Otsego Paper, Inc.",OTSEGO,MI,NaN,2022,C,Other,South Turbine 0025,"CCCT (CC (Turbine, combined cycle))",Tier1/2/3,293.90,59215.8,28.00,33.376,0.0

In [51]:
df.duplicated().sum()

0