In [227]:
import pandas as pd
import numpy as np

In [229]:
pip install pyxlsb

Requirement already satisfied: pyxlsb in d:\users\hp 15\anaconda3\lib\site-packages (1.0.10)
Note: you may need to restart the kernel to use updated packages.

In [230]:
import pandas as pd

df = pd.read_excel(
    r"C:\Users\HP 15\Desktop\deep learning project\emissions_by_unit_and_fuel_type_c_d_aa.xlsb",
    engine="pyxlsb"
)

In [232]:
df.head(10)

,This file contains data collected by the Greenhouse Gas Reporting Program for 2011-2023,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,This data was reported to EPA by facilities as...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,All emissions data is presented in units of me...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,** A file containing matches between each GHGR...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,** Additional information on facility location...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"*** Explanation about what an ""Electricity Gen...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Facility Id,FRS Id,Facility Name,City,State,Primary NAICS Code,Reporting Year,Industry Type (subparts),Industry Type (sectors),Unit Name,Unit Type,Unit Reporting Method,Unit Maximum Rated Heat Input Capacity (mmBTU/hr),Unit CO2 emissions (non-biogenic),Unit Methane (CH4) emissions,Unit Nitrous Oxide (N2O) emissions,Unit Biogenic CO2 emissions (metric tons)
6,1001155,110000397516,1500 South Tibbs LLC d/b/a Aurorium Indianapol...,Indianapolis,IN,325199,2023,C,Chemicals,GP-1,NaN,Tier1/2/3,91.8,64740.5,30.5,36.356,0
7,1012147,NaN,17Z Gas Plant - Chevron USA Inc.,McKittrick,CA,211130,2018,"C,NN,W","Natural Gas and Natural Gas Liquids Suppliers,...",CP-03.00,OCS (Other combustion source),Tier1/2/3,30,3304.7,1.5,1.788,0
8,1012147,NaN,17Z Gas Plant - Chevron USA Inc.,McKittrick,CA,211130,2018,"C,NN,W","Natural Gas and Natural Gas Liquids Suppliers,...",CP-03.01,OCS (Other combustion source),Tier1/2/3,30,0.2,0,0,0
9,1012147,NaN,17Z Gas Plant - Chevron USA Inc.,McKittrick,CA,211130,2018,"C,NN,W","Natural Gas and Natural Gas Liquids Suppliers,...",CP-03.02,OCS (Other combustion source),Tier1/2/3,30,175,0,0,0

In [235]:
df.tail()

,This file contains data collected by the Greenhouse Gas Reporting Program for 2011-2023,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
268779,1003318,110043796675,ZYBACH CRYOGENIC PLANT,Briscoe,TX,211111,2015,"C,W",Petroleum and Natural Gas Systems,GP-Zybach,OCS (Other combustion source),Tier1/2/3,32,33757.8,16,19.072,0
268780,1003318,110043796675,ZYBACH CRYOGENIC PLANT,Briscoe,TX,211111,2014,"C,W",Petroleum and Natural Gas Systems,GP-Zybach,OCS (Other combustion source),Tier1/2/3,32,32901.2,15.5,18.476,0
268781,1003318,110043796675,ZYBACH CRYOGENIC PLANT,Briscoe,TX,211111,2013,"C,W",Petroleum and Natural Gas Systems,GP-Zybach,OCS (Other combustion source),Tier1/2/3,32,42700.7,20.25,24.138,0
268782,1003318,110043796675,ZYBACH CRYOGENIC PLANT,Briscoe,TX,211111,2012,"C,W",Petroleum and Natural Gas Systems,GP-Zybach,OCS (Other combustion source),Tier1/2/3,32,46840.7,22,26.224,0
268783,1003318,110043796675,ZYBACH CRYOGENIC PLANT,Briscoe,TX,211111,2011,"C,W",Petroleum and Natural Gas Systems,GP-Zybach,OCS (Other combustion source),Tier1/2/3,32,53482.2,25.25,30.098,0

In [237]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 268784 entries, 0 to 268783
Data columns (total 17 columns):
 #   Column                                                                                   Non-Null Count   Dtype
---  ------                                                                                   --------------   -----
 0   This file contains data collected by the Greenhouse Gas Reporting Program for 2011-2023  268784 non-null  object
 1   Unnamed: 1                                                                               239089 non-null  object
 2   Unnamed: 2                                                                               268779 non-null  object
 3   Unnamed: 3                                                                               268779 non-null  object
 4   Unnamed: 4                                                                               268779 non-null  object
 5   Unnamed: 5                                                                               268763 non-null  object
 6   Unnamed: 6                                                                               268779 non-null  object
 7   Unnamed: 7                                                                               268779 non-null  object
 8   Unnamed: 8                                                                               268779 non-null  object
 9   Unnamed: 9                                                                               268779 non-null  object
 10  Unnamed: 10                                                                              259676 non-null  object
 11  Unnamed: 11                                                                              264851 non-null  object
 12  Unnamed: 12                                                                              215247 non-null  object
 13  Unnamed: 13                                                                              268779 non-null  object
 14  Unnamed: 14                                                                              268779 non-null  object
 15  Unnamed: 15                                                                              268779 non-null  object
 16  Unnamed: 16                                                                              264851 non-null  object
dtypes: object(17)
memory usage: 34.9+ MB

In [239]:
df.drop(index=df.index[:5], inplace=True)

# Set the first row as header
df.columns = df.iloc[0]

# Drop the row that became the header
df = df.iloc[1:].reset_index(drop=True)

In [241]:
df.head()

5,Facility Id,FRS Id,Facility Name,City,State,Primary NAICS Code,Reporting Year,Industry Type (subparts),Industry Type (sectors),Unit Name,Unit Type,Unit Reporting Method,Unit Maximum Rated Heat Input Capacity (mmBTU/hr),Unit CO2 emissions (non-biogenic),Unit Methane (CH4) emissions,Unit Nitrous Oxide (N2O) emissions,Unit Biogenic CO2 emissions (metric tons)
0,1001155,110000397516,1500 South Tibbs LLC d/b/a Aurorium Indianapol...,Indianapolis,IN,325199,2023,C,Chemicals,GP-1,NaN,Tier1/2/3,91.8,64740.5,30.5,36.356,0
1,1012147,NaN,17Z Gas Plant - Chevron USA Inc.,McKittrick,CA,211130,2018,"C,NN,W","Natural Gas and Natural Gas Liquids Suppliers,...",CP-03.00,OCS (Other combustion source),Tier1/2/3,30,3304.7,1.5,1.788,0
2,1012147,NaN,17Z Gas Plant - Chevron USA Inc.,McKittrick,CA,211130,2018,"C,NN,W","Natural Gas and Natural Gas Liquids Suppliers,...",CP-03.01,OCS (Other combustion source),Tier1/2/3,30,0.2,0,0,0
3,1012147,NaN,17Z Gas Plant - Chevron USA Inc.,McKittrick,CA,211130,2018,"C,NN,W","Natural Gas and Natural Gas Liquids Suppliers,...",CP-03.02,OCS (Other combustion source),Tier1/2/3,30,175,0,0,0
4,1012147,NaN,17Z Gas Plant - Chevron USA Inc.,McKittrick,CA,211130,2017,"C,NN,W","Natural Gas and Natural Gas Liquids Suppliers,...",CP-03.00,OCS (Other combustion source),Tier1/2/3,30,9106.1,4.25,5.066,0

In [243]:
df.tail()

5,Facility Id,FRS Id,Facility Name,City,State,Primary NAICS Code,Reporting Year,Industry Type (subparts),Industry Type (sectors),Unit Name,Unit Type,Unit Reporting Method,Unit Maximum Rated Heat Input Capacity (mmBTU/hr),Unit CO2 emissions (non-biogenic),Unit Methane (CH4) emissions,Unit Nitrous Oxide (N2O) emissions,Unit Biogenic CO2 emissions (metric tons)
268773,1003318,110043796675,ZYBACH CRYOGENIC PLANT,Briscoe,TX,211111,2015,"C,W",Petroleum and Natural Gas Systems,GP-Zybach,OCS (Other combustion source),Tier1/2/3,32,33757.8,16,19.072,0
268774,1003318,110043796675,ZYBACH CRYOGENIC PLANT,Briscoe,TX,211111,2014,"C,W",Petroleum and Natural Gas Systems,GP-Zybach,OCS (Other combustion source),Tier1/2/3,32,32901.2,15.5,18.476,0
268775,1003318,110043796675,ZYBACH CRYOGENIC PLANT,Briscoe,TX,211111,2013,"C,W",Petroleum and Natural Gas Systems,GP-Zybach,OCS (Other combustion source),Tier1/2/3,32,42700.7,20.25,24.138,0
268776,1003318,110043796675,ZYBACH CRYOGENIC PLANT,Briscoe,TX,211111,2012,"C,W",Petroleum and Natural Gas Systems,GP-Zybach,OCS (Other combustion source),Tier1/2/3,32,46840.7,22,26.224,0
268777,1003318,110043796675,ZYBACH CRYOGENIC PLANT,Briscoe,TX,211111,2011,"C,W",Petroleum and Natural Gas Systems,GP-Zybach,OCS (Other combustion source),Tier1/2/3,32,53482.2,25.25,30.098,0

In [245]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 268778 entries, 0 to 268777
Data columns (total 17 columns):
 #   Column                                             Non-Null Count   Dtype
---  ------                                             --------------   -----
 0   Facility Id                                        268778 non-null  object
 1   FRS Id                                             239088 non-null  object
 2   Facility Name                                      268778 non-null  object
 3   City                                               268778 non-null  object
 4   State                                              268778 non-null  object
 5   Primary NAICS Code                                 268762 non-null  object
 6   Reporting Year                                     268778 non-null  object
 7   Industry Type (subparts)                           268778 non-null  object
 8   Industry Type (sectors)                            268778 non-null  object
 9   Unit Name                                          268778 non-null  object
 10  Unit Type                                          259675 non-null  object
 11  Unit Reporting Method                              264850 non-null  object
 12  Unit Maximum Rated Heat Input Capacity (mmBTU/hr)  215246 non-null  object
 13  Unit CO2 emissions (non-biogenic)                  268778 non-null  object
 14  Unit Methane (CH4) emissions                       268778 non-null  object
 15  Unit Nitrous Oxide (N2O) emissions                 268778 non-null  object
 16  Unit Biogenic CO2 emissions (metric tons)          264850 non-null  object
dtypes: object(17)
memory usage: 34.9+ MB

In [247]:
df.isnull().sum()

5
Facility Id                                              0
FRS Id                                               29690
Facility Name                                            0
City                                                     0
State                                                    0
Primary NAICS Code                                      16
Reporting Year                                           0
Industry Type (subparts)                                 0
Industry Type (sectors)                                  0
Unit Name                                                0
Unit Type                                             9103
Unit Reporting Method                                 3928
Unit Maximum Rated Heat Input Capacity (mmBTU/hr)    53532
Unit CO2 emissions (non-biogenic)                        0
Unit Methane (CH4) emissions                             0
Unit Nitrous Oxide (N2O) emissions                       0
Unit Biogenic CO2 emissions (metric tons)             3928
dtype: int64

In [249]:
df.replace(['NaN', 'nan', 'None'], np.nan, inplace=True)

C:\Users\HP 15\AppData\Local\Temp\ipykernel_3140\3553819837.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace(['NaN', 'nan', 'None'], np.nan, inplace=True)

In [251]:
df.isnull().sum()

5
Facility Id                                              0
FRS Id                                               29690
Facility Name                                            0
City                                                     0
State                                                    0
Primary NAICS Code                                      16
Reporting Year                                           0
Industry Type (subparts)                                 0
Industry Type (sectors)                                  0
Unit Name                                                0
Unit Type                                             9103
Unit Reporting Method                                 3928
Unit Maximum Rated Heat Input Capacity (mmBTU/hr)    53532
Unit CO2 emissions (non-biogenic)                        0
Unit Methane (CH4) emissions                             0
Unit Nitrous Oxide (N2O) emissions                       0
Unit Biogenic CO2 emissions (metric tons)             3928
dtype: int64

In [253]:
df.drop("FRS Id", axis=1, inplace=True)

So this column was dropped because it has null values and the column is used as a unique I dentfiyer for that we have facility ID so we have no use for this column

In [256]:
df.isnull().sum()

5
Facility Id                                              0
Facility Name                                            0
City                                                     0
State                                                    0
Primary NAICS Code                                      16
Reporting Year                                           0
Industry Type (subparts)                                 0
Industry Type (sectors)                                  0
Unit Name                                                0
Unit Type                                             9103
Unit Reporting Method                                 3928
Unit Maximum Rated Heat Input Capacity (mmBTU/hr)    53532
Unit CO2 emissions (non-biogenic)                        0
Unit Methane (CH4) emissions                             0
Unit Nitrous Oxide (N2O) emissions                       0
Unit Biogenic CO2 emissions (metric tons)             3928
dtype: int64

In [258]:
df[df["Primary NAICS Code"].isna()]

5,Facility Id,Facility Name,City,State,Primary NAICS Code,Reporting Year,Industry Type (subparts),Industry Type (sectors),Unit Name,Unit Type,Unit Reporting Method,Unit Maximum Rated Heat Input Capacity (mmBTU/hr),Unit CO2 emissions (non-biogenic),Unit Methane (CH4) emissions,Unit Nitrous Oxide (N2O) emissions,Unit Biogenic CO2 emissions (metric tons)
14191,1013060,Arcosa Lightweight Indiana,Mooresville,IN,NaN,2022,C,Other,GP-Kilns,OCS (Other combustion source),Tier1/2/3,100.00,51520.8,24.50,29.204,0.0
25848,1000230,Blue Ridge Paper Products LLC,CANTON,NC,NaN,2022,"AA,C,TT","Pulp and Paper, Waste",GP-1,OCS (Other combustion source),Tier1/2/3,1.35,74.3,0.00,0.298,0.0
25849,1000230,Blue Ridge Paper Products LLC,CANTON,NC,NaN,2022,"AA,C,TT","Pulp and Paper, Waste",GP-2,OCS (Other combustion source),Tier1/2/3,4.00,4776.0,2.25,2.682,0.0
25850,1000230,Blue Ridge Paper Products LLC,CANTON,NC,NaN,2022,"AA,C,TT","Pulp and Paper, Waste",Lime Kiln No.4,Pulp Mill Lime Kiln,NaN,NaN,13545.6,15.75,0.298,NaN
25851,1000230,Blue Ridge Paper Products LLC,CANTON,NC,NaN,2022,"AA,C,TT","Pulp and Paper, Waste",Lime Kiln No.5,Pulp Mill Lime Kiln,NaN,NaN,25324.0,28.75,0.298,NaN
25852,1000230,Blue Ridge Paper Products LLC,CANTON,NC,NaN,2022,"AA,C,TT","Pulp and Paper, Waste",PB - No. 1 Natural Gas Package Boiler,"OB (Boiler, other)",Tier1/2/3,225.00,71903.0,34.00,40.528,0.0
25853,1000230,Blue Ridge Paper Products LLC,CANTON,NC,NaN,2022,"AA,C,TT","Pulp and Paper, Waste",PB - No. 2 Natural Gas Package Boiler,"OB (Boiler, other)",Tier1/2/3,225.00,72645.8,34.25,40.826,0.0
25854,1000230,Blue Ridge Paper Products LLC,CANTON,NC,NaN,2022,"AA,C,TT","Pulp and Paper, Waste",PB - No. 4,"PCT (Pulverized coal, tangentially-fired)",Tier1/2/3,535.00,347831.7,907.50,1571.056,0.0
25855,1000230,Blue Ridge Paper Products LLC,CANTON,NC,NaN,2022,"AA,C,TT","Pulp and Paper, Waste",PB - Riley Bark,S (Stoker Boiler),Tier1/2/3,380.00,106365.4,420.50,1335.040,74739.8
25856,1000230,Blue Ridge Paper Products LLC,CANTON,NC,NaN,2022,"AA,C,TT","Pulp and Paper, Waste",PB - Riley Coal,"PCWD (Pulverized coal, wall-fired, dry bottom)",Tier1/2/3,399.00,189537.1,467.00,804.898,0.0
25857,1000230,Blue Ridge Paper Products LLC,CANTON,NC,NaN,2022,"AA,C,TT","Pulp and Paper, Waste",Recovery Furnace No.10,Chemical Recovery Furnace,NaN,NaN,18858.4,233.50,610.602,NaN
25858,1000230,Blue Ridge Paper Products LLC,CANTON,NC,NaN,2022,"AA,C,TT","Pulp and Paper, Waste",Recovery Furnace No.11,Chemical Recovery Furnace,NaN,NaN,13029.3,253.00,663.348,NaN
70615,1005704,DUNN PAPER INC.,PORT HURON,MI,NaN,2022,C,Other,GP-Boilers & Process/Space Heaters,OCS (Other combustion source),Tier1/2/3,94.70,14038.6,6.50,7.748,0.0
172374,1000248,"Otsego Paper, Inc.",OTSEGO,MI,NaN,2022,C,Other,GP-Mill plus package boiler,OCS (Other combustion source),Tier1/2/3,242.00,727.6,0.25,0.298,0.0
172375,1000248,"Otsego Paper, Inc.",OTSEGO,MI,NaN,2022,C,Other,North Turbine 0024,"CCCT (CC (Turbine, combined cycle))",Tier1/2/3,293.90,49618.2,23.50,28.012,0.0
172376,1000248,"Otsego Paper, Inc.",OTSEGO,MI,NaN,2022,C,Other,South Turbine 0025,"CCCT (CC (Turbine, combined cycle))",Tier1/2/3,293.90,59215.8,28.00,33.376,0.0

In [260]:
df.duplicated().sum()

0

In [262]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 268778 entries, 0 to 268777
Data columns (total 16 columns):
 #   Column                                             Non-Null Count   Dtype
---  ------                                             --------------   -----
 0   Facility Id                                        268778 non-null  int64
 1   Facility Name                                      268778 non-null  object
 2   City                                               268778 non-null  object
 3   State                                              268778 non-null  object
 4   Primary NAICS Code                                 268762 non-null  object
 5   Reporting Year                                     268778 non-null  int64
 6   Industry Type (subparts)                           268778 non-null  object
 7   Industry Type (sectors)                            268778 non-null  object
 8   Unit Name                                          268778 non-null  object
 9   Unit Type                                          259675 non-null  object
 10  Unit Reporting Method                              264850 non-null  object
 11  Unit Maximum Rated Heat Input Capacity (mmBTU/hr)  215246 non-null  float64
 12  Unit CO2 emissions (non-biogenic)                  268778 non-null  float64
 13  Unit Methane (CH4) emissions                       268778 non-null  float64
 14  Unit Nitrous Oxide (N2O) emissions                 268778 non-null  float64
 15  Unit Biogenic CO2 emissions (metric tons)          264850 non-null  float64
dtypes: float64(5), int64(2), object(9)
memory usage: 32.8+ MB

In [264]:
df.head()

5,Facility Id,Facility Name,City,State,Primary NAICS Code,Reporting Year,Industry Type (subparts),Industry Type (sectors),Unit Name,Unit Type,Unit Reporting Method,Unit Maximum Rated Heat Input Capacity (mmBTU/hr),Unit CO2 emissions (non-biogenic),Unit Methane (CH4) emissions,Unit Nitrous Oxide (N2O) emissions,Unit Biogenic CO2 emissions (metric tons)
0,1001155,1500 South Tibbs LLC d/b/a Aurorium Indianapol...,Indianapolis,IN,325199,2023,C,Chemicals,GP-1,NaN,Tier1/2/3,91.8,64740.5,30.50,36.356,0.0
1,1012147,17Z Gas Plant - Chevron USA Inc.,McKittrick,CA,211130,2018,"C,NN,W","Natural Gas and Natural Gas Liquids Suppliers,...",CP-03.00,OCS (Other combustion source),Tier1/2/3,30.0,3304.7,1.50,1.788,0.0
2,1012147,17Z Gas Plant - Chevron USA Inc.,McKittrick,CA,211130,2018,"C,NN,W","Natural Gas and Natural Gas Liquids Suppliers,...",CP-03.01,OCS (Other combustion source),Tier1/2/3,30.0,0.2,0.00,0.000,0.0
3,1012147,17Z Gas Plant - Chevron USA Inc.,McKittrick,CA,211130,2018,"C,NN,W","Natural Gas and Natural Gas Liquids Suppliers,...",CP-03.02,OCS (Other combustion source),Tier1/2/3,30.0,175.0,0.00,0.000,0.0
4,1012147,17Z Gas Plant - Chevron USA Inc.,McKittrick,CA,211130,2017,"C,NN,W","Natural Gas and Natural Gas Liquids Suppliers,...",CP-03.00,OCS (Other combustion source),Tier1/2/3,30.0,9106.1,4.25,5.066,0.0

In [266]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
    .str.replace("(", "")
    .str.replace(")", "")
)

In [268]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 268778 entries, 0 to 268777
Data columns (total 16 columns):
 #   Column                                           Non-Null Count   Dtype
---  ------                                           --------------   -----
 0   facility_id                                      268778 non-null  int64
 1   facility_name                                    268778 non-null  object
 2   city                                             268778 non-null  object
 3   state                                            268778 non-null  object
 4   primary_naics_code                               268762 non-null  object
 5   reporting_year                                   268778 non-null  int64
 6   industry_type_subparts                           268778 non-null  object
 7   industry_type_sectors                            268778 non-null  object
 8   unit_name                                        268778 non-null  object
 9   unit_type                                        259675 non-null  object
 10  unit_reporting_method                            264850 non-null  object
 11  unit_maximum_rated_heat_input_capacity_mmbtu/hr  215246 non-null  float64
 12  unit_co2_emissions_non-biogenic                  268778 non-null  float64
 13  unit_methane_ch4_emissions                       268778 non-null  float64
 14  unit_nitrous_oxide_n2o_emissions                 268778 non-null  float64
 15  unit_biogenic_co2_emissions_metric_tons          264850 non-null  float64
dtypes: float64(5), int64(2), object(9)
memory usage: 32.8+ MB

In [270]:
df.isnull().sum()

5
facility_id                                            0
facility_name                                          0
city                                                   0
state                                                  0
primary_naics_code                                    16
reporting_year                                         0
industry_type_subparts                                 0
industry_type_sectors                                  0
unit_name                                              0
unit_type                                           9103
unit_reporting_method                               3928
unit_maximum_rated_heat_input_capacity_mmbtu/hr    53532
unit_co2_emissions_non-biogenic                        0
unit_methane_ch4_emissions                             0
unit_nitrous_oxide_n2o_emissions                       0
unit_biogenic_co2_emissions_metric_tons             3928
dtype: int64

In [272]:
df['unit_biogenic_co2_emissions_metric_tons'] = df['unit_biogenic_co2_emissions_metric_tons'].fillna(0)

In [274]:
df['unit_maximum_rated_heat_input_capacity_mmbtu/hr'] = df.groupby('unit_type')['unit_maximum_rated_heat_input_capacity_mmbtu/hr'].transform(
    lambda x: x.fillna(x.median())
)

In [276]:
df.isnull().sum()

5
facility_id                                            0
facility_name                                          0
city                                                   0
state                                                  0
primary_naics_code                                    16
reporting_year                                         0
industry_type_subparts                                 0
industry_type_sectors                                  0
unit_name                                              0
unit_type                                           9103
unit_reporting_method                               3928
unit_maximum_rated_heat_input_capacity_mmbtu/hr    13039
unit_co2_emissions_non-biogenic                        0
unit_methane_ch4_emissions                             0
unit_nitrous_oxide_n2o_emissions                       0
unit_biogenic_co2_emissions_metric_tons                0
dtype: int64

In [278]:
df['unit_type'] = df['unit_type'].fillna('Unknown')

In [280]:
df.isnull().sum()

5
facility_id                                            0
facility_name                                          0
city                                                   0
state                                                  0
primary_naics_code                                    16
reporting_year                                         0
industry_type_subparts                                 0
industry_type_sectors                                  0
unit_name                                              0
unit_type                                              0
unit_reporting_method                               3928
unit_maximum_rated_heat_input_capacity_mmbtu/hr    13039
unit_co2_emissions_non-biogenic                        0
unit_methane_ch4_emissions                             0
unit_nitrous_oxide_n2o_emissions                       0
unit_biogenic_co2_emissions_metric_tons                0
dtype: int64

In [282]:
col = 'unit_maximum_rated_heat_input_capacity_mmbtu/hr'

global_median = df[col].median()
df[col] = df[col].fillna(global_median)

In [284]:
df.isnull().sum()

5
facility_id                                           0
facility_name                                         0
city                                                  0
state                                                 0
primary_naics_code                                   16
reporting_year                                        0
industry_type_subparts                                0
industry_type_sectors                                 0
unit_name                                             0
unit_type                                             0
unit_reporting_method                              3928
unit_maximum_rated_heat_input_capacity_mmbtu/hr       0
unit_co2_emissions_non-biogenic                       0
unit_methane_ch4_emissions                            0
unit_nitrous_oxide_n2o_emissions                      0
unit_biogenic_co2_emissions_metric_tons               0
dtype: int64

In [286]:
# drop the column correctly using the 'columns' parameter
df.drop(columns=['unit_reporting_method'], inplace=True)

In [288]:
df.isnull().sum()

5
facility_id                                         0
facility_name                                       0
city                                                0
state                                               0
primary_naics_code                                 16
reporting_year                                      0
industry_type_subparts                              0
industry_type_sectors                               0
unit_name                                           0
unit_type                                           0
unit_maximum_rated_heat_input_capacity_mmbtu/hr     0
unit_co2_emissions_non-biogenic                     0
unit_methane_ch4_emissions                          0
unit_nitrous_oxide_n2o_emissions                    0
unit_biogenic_co2_emissions_metric_tons             0
dtype: int64

In [290]:
df['primary_naics_code'] = df['primary_naics_code'].fillna('Unknown')

In [292]:
df.isnull().sum()

5
facility_id                                        0
facility_name                                      0
city                                               0
state                                              0
primary_naics_code                                 0
reporting_year                                     0
industry_type_subparts                             0
industry_type_sectors                              0
unit_name                                          0
unit_type                                          0
unit_maximum_rated_heat_input_capacity_mmbtu/hr    0
unit_co2_emissions_non-biogenic                    0
unit_methane_ch4_emissions                         0
unit_nitrous_oxide_n2o_emissions                   0
unit_biogenic_co2_emissions_metric_tons            0
dtype: int64

In [294]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 268778 entries, 0 to 268777
Data columns (total 15 columns):
 #   Column                                           Non-Null Count   Dtype
---  ------                                           --------------   -----
 0   facility_id                                      268778 non-null  int64
 1   facility_name                                    268778 non-null  object
 2   city                                             268778 non-null  object
 3   state                                            268778 non-null  object
 4   primary_naics_code                               268778 non-null  object
 5   reporting_year                                   268778 non-null  int64
 6   industry_type_subparts                           268778 non-null  object
 7   industry_type_sectors                            268778 non-null  object
 8   unit_name                                        268778 non-null  object
 9   unit_type                                        268778 non-null  object
 10  unit_maximum_rated_heat_input_capacity_mmbtu/hr  268778 non-null  float64
 11  unit_co2_emissions_non-biogenic                  268778 non-null  float64
 12  unit_methane_ch4_emissions                       268778 non-null  float64
 13  unit_nitrous_oxide_n2o_emissions                 268778 non-null  float64
 14  unit_biogenic_co2_emissions_metric_tons          268778 non-null  float64
dtypes: float64(5), int64(2), object(8)
memory usage: 30.8+ MB

In [296]:
df.dtypes

5
facility_id                                          int64
facility_name                                       object
city                                                object
state                                               object
primary_naics_code                                  object
reporting_year                                       int64
industry_type_subparts                              object
industry_type_sectors                               object
unit_name                                           object
unit_type                                           object
unit_maximum_rated_heat_input_capacity_mmbtu/hr    float64
unit_co2_emissions_non-biogenic                    float64
unit_methane_ch4_emissions                         float64
unit_nitrous_oxide_n2o_emissions                   float64
unit_biogenic_co2_emissions_metric_tons            float64
dtype: object

In [298]:
# Drop facility_id and unit_name safely
df = df.drop(columns=['facility_id', 'unit_name'], errors='ignore')

# Verify the result
print(df.columns.tolist())

['facility_name', 'city', 'state', 'primary_naics_code', 'reporting_year', 'industry_type_subparts', 'industry_type_sectors', 'unit_type', 'unit_maximum_rated_heat_input_capacity_mmbtu/hr', 'unit_co2_emissions_non-biogenic', 'unit_methane_ch4_emissions', 'unit_nitrous_oxide_n2o_emissions', 'unit_biogenic_co2_emissions_metric_tons']

In [300]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 268778 entries, 0 to 268777
Data columns (total 13 columns):
 #   Column                                           Non-Null Count   Dtype
---  ------                                           --------------   -----
 0   facility_name                                    268778 non-null  object
 1   city                                             268778 non-null  object
 2   state                                            268778 non-null  object
 3   primary_naics_code                               268778 non-null  object
 4   reporting_year                                   268778 non-null  int64
 5   industry_type_subparts                           268778 non-null  object
 6   industry_type_sectors                            268778 non-null  object
 7   unit_type                                        268778 non-null  object
 8   unit_maximum_rated_heat_input_capacity_mmbtu/hr  268778 non-null  float64
 9   unit_co2_emissions_non-biogenic                  268778 non-null  float64
 10  unit_methane_ch4_emissions                       268778 non-null  float64
 11  unit_nitrous_oxide_n2o_emissions                 268778 non-null  float64
 12  unit_biogenic_co2_emissions_metric_tons          268778 non-null  float64
dtypes: float64(5), int64(1), object(7)
memory usage: 26.7+ MB

In [302]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

# 1. Define the categorical columns to encode (exclude facility_name)
categorical_cols = [
    'city',
    'state',
    'primary_naics_code',
    'industry_type_subparts',
    'industry_type_sectors',
    'unit_type'
]

# 2. Dictionary to store the fitted encoders for later use
encoders = {}

# 3. Loop through columns and encode
for col in categorical_cols:
    le = LabelEncoder()  # Initialize a new encoder for each column
    df[col + '_Encoded'] = le.fit_transform(df[col].astype(str))
    encoders[col] = le  # Store encoder for inverse transform if needed

# 4. Verify result
df.head()

5,facility_name,city,state,primary_naics_code,reporting_year,industry_type_subparts,industry_type_sectors,unit_type,unit_maximum_rated_heat_input_capacity_mmbtu/hr,unit_co2_emissions_non-biogenic,unit_methane_ch4_emissions,unit_nitrous_oxide_n2o_emissions,unit_biogenic_co2_emissions_metric_tons,city_Encoded,state_Encoded,primary_naics_code_Encoded,industry_type_subparts_Encoded,industry_type_sectors_Encoded,unit_type_Encoded
0,1500 South Tibbs LLC d/b/a Aurorium Indianapol...,Indianapolis,IN,325199,2023,C,Chemicals,Unknown,14.52,64740.5,30.50,36.356,0.0,1937,16,141,9,1,49
1,17Z Gas Plant - Chevron USA Inc.,McKittrick,CA,211130,2018,"C,NN,W","Natural Gas and Natural Gas Liquids Suppliers,...",OCS (Other combustion source),30.00,3304.7,1.50,1.788,0.0,2653,4,7,93,45,28
2,17Z Gas Plant - Chevron USA Inc.,McKittrick,CA,211130,2018,"C,NN,W","Natural Gas and Natural Gas Liquids Suppliers,...",OCS (Other combustion source),30.00,0.2,0.00,0.000,0.0,2653,4,7,93,45,28
3,17Z Gas Plant - Chevron USA Inc.,McKittrick,CA,211130,2018,"C,NN,W","Natural Gas and Natural Gas Liquids Suppliers,...",OCS (Other combustion source),30.00,175.0,0.00,0.000,0.0,2653,4,7,93,45,28
4,17Z Gas Plant - Chevron USA Inc.,McKittrick,CA,211130,2017,"C,NN,W","Natural Gas and Natural Gas Liquids Suppliers,...",OCS (Other combustion source),30.00,9106.1,4.25,5.066,0.0,2653,4,7,93,45,28

In [304]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 268778 entries, 0 to 268777
Data columns (total 19 columns):
 #   Column                                           Non-Null Count   Dtype
---  ------                                           --------------   -----
 0   facility_name                                    268778 non-null  object
 1   city                                             268778 non-null  object
 2   state                                            268778 non-null  object
 3   primary_naics_code                               268778 non-null  object
 4   reporting_year                                   268778 non-null  int64
 5   industry_type_subparts                           268778 non-null  object
 6   industry_type_sectors                            268778 non-null  object
 7   unit_type                                        268778 non-null  object
 8   unit_maximum_rated_heat_input_capacity_mmbtu/hr  268778 non-null  float64
 9   unit_co2_emissions_non-biogenic                  268778 non-null  float64
 10  unit_methane_ch4_emissions                       268778 non-null  float64
 11  unit_nitrous_oxide_n2o_emissions                 268778 non-null  float64
 12  unit_biogenic_co2_emissions_metric_tons          268778 non-null  float64
 13  city_Encoded                                     268778 non-null  int32
 14  state_Encoded                                    268778 non-null  int32
 15  primary_naics_code_Encoded                       268778 non-null  int32
 16  industry_type_subparts_Encoded                   268778 non-null  int32
 17  industry_type_sectors_Encoded                    268778 non-null  int32
 18  unit_type_Encoded                                268778 non-null  int32
dtypes: float64(5), int32(6), int64(1), object(7)
memory usage: 32.8+ MB

In [312]:
df = df.drop(columns=[
    'city', 'state', 'primary_naics_code',
    'industry_type_subparts', 'industry_type_sectors',
    'unit_type'
])

In [314]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 268778 entries, 0 to 268777
Data columns (total 13 columns):
 #   Column                                           Non-Null Count   Dtype
---  ------                                           --------------   -----
 0   facility_name                                    268778 non-null  object
 1   reporting_year                                   268778 non-null  int64
 2   unit_maximum_rated_heat_input_capacity_mmbtu/hr  268778 non-null  float64
 3   unit_co2_emissions_non-biogenic                  268778 non-null  float64
 4   unit_methane_ch4_emissions                       268778 non-null  float64
 5   unit_nitrous_oxide_n2o_emissions                 268778 non-null  float64
 6   unit_biogenic_co2_emissions_metric_tons          268778 non-null  float64
 7   city_Encoded                                     268778 non-null  int32
 8   state_Encoded                                    268778 non-null  int32
 9   primary_naics_code_Encoded                       268778 non-null  int32
 10  industry_type_subparts_Encoded                   268778 non-null  int32
 11  industry_type_sectors_Encoded                    268778 non-null  int32
 12  unit_type_Encoded                                268778 non-null  int32
dtypes: float64(5), int32(6), int64(1), object(1)
memory usage: 20.5+ MB

In [318]:
df.dtypes

5
facility_name                                       object
reporting_year                                       int64
unit_maximum_rated_heat_input_capacity_mmbtu/hr    float64
unit_co2_emissions_non-biogenic                    float64
unit_methane_ch4_emissions                         float64
unit_nitrous_oxide_n2o_emissions                   float64
unit_biogenic_co2_emissions_metric_tons            float64
city_Encoded                                         int32
state_Encoded                                        int32
primary_naics_code_Encoded                           int32
industry_type_subparts_Encoded                       int32
industry_type_sectors_Encoded                        int32
unit_type_Encoded                                    int32
dtype: object

In [326]:
# Normalize column names (remove leading/trailing spaces)
df.columns = df.columns.str.strip()

# Create target variable: Total CO2-equivalent
# GWP: CH4 = 25, N2O = 298
df['Total_CO2e'] = (
    df['unit_co2_emissions_non-biogenic']
    + df['unit_biogenic_co2_emissions_metric_tons']
    + df['unit_methane_ch4_emissions'] * 25
    + df['unit_nitrous_oxide_n2o_emissions'] * 298
)

In [328]:
df.head()

5,facility_name,reporting_year,unit_maximum_rated_heat_input_capacity_mmbtu/hr,unit_co2_emissions_non-biogenic,unit_methane_ch4_emissions,unit_nitrous_oxide_n2o_emissions,unit_biogenic_co2_emissions_metric_tons,city_Encoded,state_Encoded,primary_naics_code_Encoded,industry_type_subparts_Encoded,industry_type_sectors_Encoded,unit_type_Encoded,Total_CO2e
0,1500 South Tibbs LLC d/b/a Aurorium Indianapol...,2023,14.52,64740.5,30.50,36.356,0.0,1937,16,141,9,1,49,76337.088
1,17Z Gas Plant - Chevron USA Inc.,2018,30.00,3304.7,1.50,1.788,0.0,2653,4,7,93,45,28,3875.024
2,17Z Gas Plant - Chevron USA Inc.,2018,30.00,0.2,0.00,0.000,0.0,2653,4,7,93,45,28,0.200
3,17Z Gas Plant - Chevron USA Inc.,2018,30.00,175.0,0.00,0.000,0.0,2653,4,7,93,45,28,175.000
4,17Z Gas Plant - Chevron USA Inc.,2017,30.00,9106.1,4.25,5.066,0.0,2653,4,7,93,45,28,10722.018

In [330]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 268778 entries, 0 to 268777
Data columns (total 14 columns):
 #   Column                                           Non-Null Count   Dtype
---  ------                                           --------------   -----
 0   facility_name                                    268778 non-null  object
 1   reporting_year                                   268778 non-null  int64
 2   unit_maximum_rated_heat_input_capacity_mmbtu/hr  268778 non-null  float64
 3   unit_co2_emissions_non-biogenic                  268778 non-null  float64
 4   unit_methane_ch4_emissions                       268778 non-null  float64
 5   unit_nitrous_oxide_n2o_emissions                 268778 non-null  float64
 6   unit_biogenic_co2_emissions_metric_tons          268778 non-null  float64
 7   city_Encoded                                     268778 non-null  int32
 8   state_Encoded                                    268778 non-null  int32
 9   primary_naics_code_Encoded                       268778 non-null  int32
 10  industry_type_subparts_Encoded                   268778 non-null  int32
 11  industry_type_sectors_Encoded                    268778 non-null  int32
 12  unit_type_Encoded                                268778 non-null  int32
 13  Total_CO2e                                       268778 non-null  float64
dtypes: float64(6), int32(6), int64(1), object(1)
memory usage: 22.6+ MB

In [336]:
from sklearn.preprocessing import MinMaxScaler

# Scale the feature
scaler_capacity = MinMaxScaler()
df['Capacity_Scaled'] = scaler_capacity.fit_transform(
    df[['unit_maximum_rated_heat_input_capacity_mmbtu/hr']]
)

# Scale the target
scaler_target = MinMaxScaler()
df['Total_CO2e_Scaled'] = scaler_target.fit_transform(
    df[['Total_CO2e']]
)

In [338]:
df.head()

5,facility_name,reporting_year,unit_maximum_rated_heat_input_capacity_mmbtu/hr,unit_co2_emissions_non-biogenic,unit_methane_ch4_emissions,unit_nitrous_oxide_n2o_emissions,unit_biogenic_co2_emissions_metric_tons,city_Encoded,state_Encoded,primary_naics_code_Encoded,industry_type_subparts_Encoded,industry_type_sectors_Encoded,unit_type_Encoded,Total_CO2e,Capacity_Scaled,Total_CO2e_Scaled
0,1500 South Tibbs LLC d/b/a Aurorium Indianapol...,2023,14.52,64740.5,30.50,36.356,0.0,1937,16,141,9,1,49,76337.088,9.877551e-08,1.676338e-03
1,17Z Gas Plant - Chevron USA Inc.,2018,30.00,3304.7,1.50,1.788,0.0,2653,4,7,93,45,28,3875.024,2.040816e-07,8.509428e-05
2,17Z Gas Plant - Chevron USA Inc.,2018,30.00,0.2,0.00,0.000,0.0,2653,4,7,93,45,28,0.200,2.040816e-07,4.391935e-09
3,17Z Gas Plant - Chevron USA Inc.,2018,30.00,175.0,0.00,0.000,0.0,2653,4,7,93,45,28,175.000,2.040816e-07,3.842943e-06
4,17Z Gas Plant - Chevron USA Inc.,2017,30.00,9106.1,4.25,5.066,0.0,2653,4,7,93,45,28,10722.018,2.040816e-07,2.354521e-04